== Intermediate iOS Development

=== Pro Core Data for iOS: Data Access and Persistence Engine for iPhone, iPad, and iPod touch

_Apress_
_By Michael Privat & Rob Warner_
_ISBN: 9781430233558_
_January 2011_
_$39.99 US_
_394 pages_

Based on the relatively new Cocoa touch set of APIs and libraries, the Core Data framework is now available and accessible for app development and use on iPhone, iPad, and iPod touch devices. This book explains how to use the Core Data framework for iOS, from simple to advanced techniques. Covering common and advanced persistence patterns, this book prepares any iOS developer to store and retrieve data accurately and efficiently for their iOS applications.

_http://my.safaribooksonline.com/book/programming/iphone/9781430233558?cid=1107-bibilio-ios-link[Read it on Safari Online Books]_

=== Professional iPhone and iPad Database Application Programming

_Wrox_
_By Patrick Alessi_
_ISBN: 9780470636176_
_October 2010_
_$44.99 pages_
_401 pages_

An enormous demand exists for getting iPhone applications into the enterprise and this book guides you through all the necessary steps for integrating an iPhone app within an existing enterprise. Experienced iPhone developers will learn how to take advantage of the built-in capabilities of the iPhone to confidently implement a data-driven application for the iPhone. This book gets you up to speed on developing data-driven applications for the iPhone.

_http://my.safaribooksonline.com/book/programming/iphone/9780470636176?cid=1107-bibilio-ios-link[Read it on Safari Online Books]_


=== iPhone Cool Projects

_Apress_
_By Wolfgang Ante, Gary Bennett, Benjamin Jackson, Neil Mix, Steven Peterson, Matthew Rosenfeld & Michael Ash_
_ISBN: 9781430223573_
_August 2009_
_$39.99 US_
_240 pages_

This book is written by authors who have created successful iPhone applications. Follow along and learn about multitouch controls, spatial app interaction, geo-location, cocos2d, 2d gaming, Core Location, streaming audio and how to optimize your use of limited screen real estate. Software development can be hard work. Introductory books lay the foundation, but it can be challenging to understand where to go next. This book shows some of the pieces that can be brought together to make complete, cool applications for all iPhone application developers with any level of experience or coming from any development platform.

_http://my.safaribooksonline.com/book/programming/iphone/9781430223573?cid=1107-bibilio-ios-link[Read it on Safari Online Books]_

=== Programming iOS 4

_O'Reilly Media_
_By Matt Neuberg_
_ISBN: 9781449388430_
_May 2011_
_$49.99 US_
_834 pages_

Whether you're learning Cocoa programming for the first time, or want a reference to bolster the iPhone development skills you already have, this in-depth guide provides a complete learning path -- from language basics and using Xcode and Interface Builder to all of the steps necessary for developing your app with the Cocoa framework. You'll learn everything you need to take an iPhone, iPad, or iPod touch app from initial concept to the App Store.

_http://my.safaribooksonline.com/book/programming/iphone/9781449397302?cid=1107=bibilio-ios-link[Read it on Safari Online Books]_

=== iOS 5 Sensor Programming Rough Cuts Version: Augmented Reality and Location Enabled iPhone and iPad Apps

_O'Reilly Media_
_By Alasdair Allan_
_ISBN: 9781449382650_
_December 2011_
_$39.99_
_320 pages_

Use iPhone's onboard sensors to build cutting-edge location-based and augmented reality apps. With this book, you'll learn how to combine input from the three-axis accelerometer, GPS, digital compass, and camera with outside data sets to create apps that interact with the physical world. It's ideal for experienced iPhone programmers, game programmers, augmented reality programmers, and geo hackers. This book is still in progress, but you can get going on this technology through our Rough Cuts edition, which lets you read the manuscript as it's being written, either online or via PDF.


=== Basic Sensors in iOS

_O'Reilly Media_
_By Alasdair Allan_
_ISBN: 9781449308469_
_July 2011_
_$19.99 US_
_50 pages_

Modern mobile platforms, such as Apple’s iPhone and iPad, come with a growing range of sensors; GPS, accelerometers, magnetometers and gyroscopes. This book guides you through how to make use of these sensors, giving you the necessary tools and experience to develop applications that makes best use of the hardware.

=== Core Audio

_Addison-Wesley Professional_
_By Kevin Avila & Chris Adamson_
_ISBN: 9780321636843_
_September 2011_
_$44.99_
_300 pages_

This book will teach you all you need to know about Core Audio. Core Audio lets you write applications that work directly with the uncompressed audio data captured from a microphone, perform effects on it, mix it with other audio, and play the result out to the speakers and/or convert it into a compressed format that you can then write to the file system or send over the network. Or, if you’re not developing full applications, Core Audio lets you write just the custom effect and wrap it in a plug-in called an audio unit, which lets users add your effect to their Core Audio-based applications. By the time you get to the end of this book, you’ll have an appreciation for just how much Core Audio does for you. This book assumes a working knowledge of C, including pointers, malloc(), and the usual hazards of low-level memory management. The book also assumes that you're familiar and comfortable with Xcode and programming in Objective-C.

_http://my.safaribooksonline.com/book/programming/iphone/9780321636843?cid=1107-bibilio-ios-link[Read it on Safari Online Books]_

=== Learning Quartz Composer: A Hands-on Guide to Creating Motion Graphics with Quartz Composer

_Addison-Wesley Professional_
_By Graham Robinson, Surya Buchwald_
_ISBN: 9780321636942_
_October 2011_
_$39.99 US_
_250 pages_

=== Learning Cocos2D: A Hands-On Guide to Building iOS Games with Cocos2D, Box2D, and Chipmunk

_Addison-Wesley Professional_
_By Rod Strougo & Ray Wenderlich_
_ISBN: 9780321735621_
_July 2011_
_$44.99 US_
_640 pages_

Follow along in this book to learn how to build the next great iOS game with Cocos2D. Cocos2D is the powerhouse framework behind some of the most popular games in the App Store. If you’ve played Tiny Wings, Angry Birds, Mega Jump, Trainyard, or even Super Turbo Action Pig, then you’ve played a game that uses Cocos2D or Box2D physics. The beauty of Cocos2D is its simplicity, and how it makes game development fun and easy. This book walks you through the process of building Space Viking (which is free on the App Store), a 2D scrolling game that leverages Cocos2D, Box2D, and Chipmunk. As you build Space Viking, you’ll learn everything you need to know about Cocos2D so you can create the next killer iOS game.

_http://my.safaribooksonline.com/book/programming/iphone/9780321735621?cid=1107-bibilio-ios-link[Read it on Safari Online Books]_

=== Programming iOS Sensors

_Addison-Wesley Professional_
_By Eric Busch_
_ISBN: 9780321775047_
_August 2011_
_$34.99 US_
_300 pages_


=== Learning MonoTouch: A Hands-On Guide to Building iOS Applications with C# and .NET

_Addison-Wesley Professional_
_By Michael Bluestein_
_ISBN: 9780321719928_
_July 2011_
_$44.99 US_
_448 pages_

Many .NET developers and many enterprises would like to target iOS devices, yet the learning curve and cost of moving to Objective-C precludes the practicality of this in many cases. MonoTouch brings the best of CocoaTouch and .NET under a single, extensible technology, providing the only way to develop iOS applications using .NET that can be published to the iOS App Store. This book assumes the reader is familiar with C# and .NET at least on an intermediate level and focuses on making use of existing skills, while presenting iOS-specific information in detail. After the basics are covered, the book quickly moves into more complex examples that address common use cases encountered in iOS development.

_http://my.safaribooksonline.com/book/programming/iphone/9780321719928?cid=1107-bibilio-ios-link[Read it on Safari Online Books]_

=== iPhone in Practice

_Manning_
_By Bear P. Cahill_
_ISBN: 9781935182658_
_November 2011_
_$44.99 US_
_325 pages_

Forums, blogs and even the Apple Develop site are full of hard questions and murky answers. Navigating the iOS Dev Center, iOS Provisioning Portal, and iTunes Connect can be equally frustrating. When you're building an app, you don't want vague ideas and untested theory-you want real answers to real problems. You want iPhone in Practice.

iPhone in Practice is a book written from the hard-won experience of expert mobile app developer Bear Cahill. In this unique hands-on guide, you'll explore seven real, working iPhone and iPad apps and uncover nearly 100 specific techniques to solve the specific problems you'll encounter over and over. You'll dig into the practical nuts and bolts of applying views, view controllers, table views and cells, audio, graphics, images, file structure, and so on-the foundations of almost all your apps. You'll also crack some of the more difficult issues that will set you apart from the pack.

=== iOS4 in Action

_Manning_
_By Jocelyn Harrington, Brandon Trebitowski, Christopher Allen, and Shannon Appelcline_
_ISBN: 9781617290015_
_June 2011_
_$44.99 US_
_504 pages_

iOS 4 in Action, written for Xcode 4 and using the iOS SDK 4.3, is a detailed, hands-on guide that goes from setting up your development environment, through your first coding steps, all the way to creating a polished, commercial iOS 4 application. You'll run through examples from a variety of areas including a chat client, a video game, an interactive map, and background audio. You'll also learn how the new iOS 4 features apply to your existing iOS 3 based apps. This book will help you become a confident, well-rounded iOS 4 developer.


=== More iPhone 3 Development: Tackling iPhone SDK 3

_Apress_
_By Dave Mark; Jeff LaMarche_
_ISBN: 9781430225058_
_January 2010_
_$39.99 US_
_552 pages_

This book digs deeper into Apple’s latest SDK. Best-selling authors Dave Mark and Jeff LaMarche explain concepts as only they can, covering topics like Core Data, peer-to-peer networking using GameKit and network streams, working with data from the web, MapKit, in-application e-mail, and more. All the concepts and APIs are clearly presented with code snippets you can customize and use, as you like, in your own apps. Jeff and Dave carefully step through each of the Core Data concepts and show you techniques and tips specifically for writing larger applications—offering a breadth of coverage you won't find anywhere else. This book covers a variety of networking mechanisms, from GameKit’s relatively simple BlueTooth peer-to-peer model, to the addition of Bonjour discovery and network streams, through the complexity of accessing files via the web. Whether you are a relative newcomer to iPhone development or an old hand looking to expand your horizons, there’s something for everyone in this book.

_http://my.safaribooksonline.com/book/programming/iphone/9781430225058?cid=1107-bibilio-ios-link[Read it on Safari Online Books]_

=== iPhone and iOS 4 Advanced App Development: Learn by Video (video)

_Peachpit Press_
_By Turrall video2brain_
_ISBN: 9780132808651_
_July 2011_

This innovative product uses interactive video to show iOS developers how to integrate rich features that end-users have come to expect from apps, using the iOS Core Location and Mapping features and camera data. This video reviews the main features of XCode 4 as well as the more advanced APIs available to developers. Creating Universal Apps will let users broaden their audiences to the iPhone, iPod Touch, and iPad. Experienced instructor Robert Turall presents up to four hours of exceptional video training, complete with lesson files, assessment quizzes, and review materials. The video is wrapped in a unique interface that allows the viewer to jump to any topic and also bookmark individual sections for later review.

_http://my.safaribooksonline.com/book/programming/iphone/9780132808651?cid=1107-bibilio-ios-link[See it on Safari Online Books]_

=== Geolocation in iOS

_O'Reilly Media_
_By Alasdair Allan_
_ISBN: 9781449308445_
_July 2011_
_$19.99 US_
_50 pages_

The iPhone and iPad allow user positioning via multiple methods, including GPS. The growing number of location-aware, and location-fenced, applications now arriving in the App Store make heavy use of these abilities. This book walks you through the basic tools you need to build geo-aware applications before diving into the available third-party geo-SDKs available for the iOS platform.


=== iOS and Sensor Networks

_O'Reilly Media_
_By Alasdair Allan_
_ISBN: 9781449308483_
_August 2011_
_$19.99 US_
_50 pages_

This book looks at how to integrate iOS devices into distributed sensors network, both to make use of its own on-board sensors in such networks, but also as a hub. Beyond the discussion of basic client-server architectures, and making use of the existing wireless capabilities, this book examines how to connect iOS devices to microcontroller platforms via serial connections.
